version: '3.8'

services:
  kararos-postgres:
    image: postgres:16-alpine
    container_name: kararos_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: kararos_user
      POSTGRES_PASSWORD: kararos1234
      POSTGRES_DB: kararos_db
    ports:
      - "5432:5432"
    volumes:
      - kararos_pgdata:/var/lib/postgresql/data

volumes:
  kararos_pgdata:
